/* TODO: Colocar keys cuando esten listas */
export const labels = [
  { name: "Course", key: "name" },
  { name: "Code", key: "code" },
  { name: "Category", key: "category" },
  { name: "Fecha", key: "date__ini" },
  { name: "N.Inscritos", key: "n_inscritos" },
  { name: "Capac.", key: "capac" },
  { name: "Director", key: "teacher" },
  { name: "Estado", key: "state" },
  { name: "Details", key: "" },
  { name: "Legal", key: "" },
  { name: "", key: "" },
];

export const dataFake = [
  {
    id: 1,
    name: "TMA",
    code: "TMA8689",
    category: "AMD I",
    date_ini: "Marzo 2021",
    n_inscritos: 17,
    capac: 20,
    teacher: "Garrido A",
    status: true,
    state: "En curso",
  },
  {
    id: 2,
    name: "TMA",
    code: "TMA8689",
    category: "AMD I",
    date_ini: "Marzo 2021",
    n_inscritos: 17,
    capac: 20,
    teacher: "Garrido A",
    status: true,
    state: "Sin inicio",
  },
  {
    id: 2,
    name: "TMA",
    code: "TMA8689",
    category: "AMD I",
    date_ini: "Marzo 2021",
    n_inscritos: 17,
    capac: 20,
    teacher: "Garrido A",
    status: true,
    state: "En proceso",
  },

  {
    id: 4,
    name: "Comercial ",
    code: "u202415",
    category: "AMD II",
    date_ini: "Marzo 2021",
    n_inscritos: 17,
    capac: 20,
    teacher: "Garrido A",
    status: false,
    state: "Finalizado",
  },
  {
    id: 5,
    name: "Comercial ",
    code: "u202415",
    category: "AMD II",
    date_ini: "Marzo 2021",
    n_inscritos: 17,
    capac: 20,
    teacher: "Garrido A",
    status: false,
    state: "Finalizado",
  },
];
