/* TODO: Delete when using queryApi */
export const dataFake = {
  id: 1,
  name: "Turbohélices",
  code: "C12458",
  category: "Upgrade",
  date_ini: "12 Marzo 2021",
  date_end: "31 Marzo 2021",
  n_inscritos: 10,
  capac: 10,
  teacher: "Garrido A",
  status: true,
  state: "En curso",
};

/* TODO: Delete when using queryApi */
export const temarioFake = {
  code: "TMA8689",
  director: "Kevin Urbina",
  country: "Peru",
  license: "525252 HYD",
  hours: 30,
  days: 12,
  mod: "Online",
  date_ini: "12 abril de 2021",
  date_end: "30 abril de 2021",
};

/* TODO: Delete when using queryApi */
export const alumnoCourse = [
  {
    id: 1,
    name: "Renzo Abanto",
    image: "",
    country: "Perú",
    email: "kevin@sector.aeronautico",
    course: "A320",
    condition: false,
    state: "En curso",
    progress: 75,
    total_asistencia: 15,
    asistencia: 8,
    test_01: 95,
    test_02: 0,
    proyect: 0,
    prom: 0,
    inasistencia: 1,
    total: 0,
  },
  {
    id: 2,
    name: "Paola Abascal",
    image: "",
    country: "Perú",
    email: "sara@sector.aeronautico",
    course: "A320",
    condition: false,
    state: "En curso",
    progress: 75,
    total_asistencia: 15,
    asistencia: 8,
    test_01: 95,
    test_02: 0,
    proyect: 0,
    prom: 0,
    inasistencia: 1,
    total: 0,
  },
  {
    id: 3,
    name: "Franco Urbina",
    image: "",
    country: "Perú",
    email: "arian@sector.aeronautico",
    course: "A320",
    condition: true,
    state: "Finalizado",
    progress: 75,
    total_asistencia: 15,
    asistencia: 8,
    test_01: 95,
    test_02: 0,
    proyect: 0,
    prom: 0,
    inasistencia: 1,
    total: 0,
  },
];

export const labels = [
  "Integrante",
  "Country",
  "Correo",
  "Curso",
  "Condición",
  "Estado",
  "Avance %",
  "Asistencia",
  "Test 1",
  "Test 2",
  "Proyect",
  "Prom",
  "Inast.",
  "P.Total",
  "Progreso",
];
