/* TODO: Colocar keys cuando esten listas */
export const labels = [
  { name: 'Course', key: 'name' },
  { name: 'Code', key: 'code' },
  { name: 'Category', key: 'category' },
  { name: 'Fecha de inicio', key: 'date_ini' },
  { name: 'N.Inscritos', key: 'n_inscritos' },
  { name: 'Capac.', key: 'capac' },
  { name: 'Intructor', key: 'teacher' },
  { name: 'Estado', key: 'status' },
  { name: 'Details', key: '' },
  { name: 'Legal', key: '' },
  { name: '', key: '' },
]

export const dataFake = [
  {
    id: 5,
    name: 'Turbohélices',
    code: 'C12458',
    category: 'Upgrade',
    date_ini: 'Marzo 2021',
    n_inscritos: 10,
    capac: 10,
    teacher: 'Garrido A',
    status: true,
    state: 'En curso',
  },
  {
    id: 1,
    name: 'Turbohélices 2',
    code: 'C12458',
    category: 'Upgrade',
    date_ini: 'Marzo 200',
    n_inscritos: 10,
    capac: 10,
    teacher: 'Garrido A',
    status: true,
    state: 'En proceso',
  },
  {
    id: 2,
    name: 'Turbohélices 2',
    code: 'C12458',
    category: 'Upgrade',
    date_ini: 'Marzo 200',
    n_inscritos: 10,
    capac: 10,
    teacher: 'Garrido A',
    status: true,
    state: 'Sin inicio',
  },
  {
    id: 3,
    name: 'Turbohélices 2',
    code: 'C12458',
    category: 'Upgrade',
    date_ini: 'Marzo 200',
    n_inscritos: 10,
    capac: 10,
    teacher: 'Garrido A',
    status: false,
    state: 'Finalizado',
  },
  {
    id: 4,
    name: 'Turbohélices 2',
    code: 'C12458',
    category: 'Upgrade',
    date_ini: 'Marzo 200',
    n_inscritos: 10,
    capac: 10,
    teacher: 'Garrido A',
    status: false,
    state: 'Finalizado',
  },
]
